export default [
  {
    id: "1",
    author: "Wagner Esser",
    tagPictureUrl: "wagneresser",
    hashtags: [],
    likes: "",
    description: "",
    place: "Joinville",
  },
  {
    id: "2",
    author: "Mario Souto",
    tagPictureUrl: "omariosouto",
    hashtags: [],
    likes: "",
    description: "",
    place: "São Francisco do Sul",
  },
  {
    id: "3",
    author: "Vanessa Weber Fróes",
    tagPictureUrl: "vweberfroes",
    hashtags: [],
    likes: "",
    description: "",
    place: "Garuva",
  },
  {
    id: "4",
    author: "Gabriel Fróes",
    tagPictureUrl: "gabrielfroes",
    hashtags: [],
    likes: "",
    description: "São Paulo",
    place: "",
  },
  {
    id: "5",
    author: "Paulo Silveira",
    tagPictureUrl: "peas",
    hashtags: [],
    likes: "",
    description: "",
    place: "Rio de Janeiro",
  },
];
