export default [
  {
    id: "1",
    author: "Wagner Esser",
    tagPictureUrl: "wagneresser",
    hashtags: ['instagram', 'perfil', 'reactNative'],
    likes: "123",
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    place: "Joinville",
  },
  {
    id: "2",
    author: "Mario Souto",
    tagPictureUrl: "omariosouto",
    hashtags: ['allura', 'dev', 'react', 'reactNative'],
    likes: "234",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    place: "São Francisco do Sul",
  },
  {
    id: "3",
    author: "Vanessa Weber Fróes",
    tagPictureUrl: "vweberfroes",
    hashtags: ['allura', 'dev', 'react', 'reactNative'],
    likes: "1.543",
    description: "",
    place: "Garuva",
  },
  {
    id: "4",
    author: "Gabriel Fróes",
    tagPictureUrl: "gabrielfroes",
    hashtags: ['allura', 'dev', 'react', 'reactNative'],
    likes: "335",
    description: "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    place: "",
  },
  {
    id: "5",
    author: "Paulo Silveira",
    tagPictureUrl: "peas",
    hashtags: ['allura', 'dev', 'react', 'reactNative'],
    likes: "231",
    description: "It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    place: "",
  },
];
